### ISSUE TITLE
Pypi release out of date

### ISSUE THREAD

**Issue by MrBlenny** [fishbotics/urchin#19]
Hola,
Just flagging that the Pypi release is out of date with the code on github. Would be great if this could be bumped

**Comment by traversaro** [comment]
Thanks for reporting this @MrBlenny ! PR https://github.com/fishbotics/urchin/pull/23 should fix it, once it is merged we can do a release.

**Comment by traversaro** [comment]
The release was tagged, but we still have an upload problem: https://github.com/fishbotics/urchin/issues/24 .

**Comment by traversaro** [comment]
The latest release is available on PyPI: https://pypi.org/project/urchin/0.0.29/ .
