### ISSUE TITLE
pycollada strict pin to 0.6.0 ? 

### ISSUE THREAD

**Issue by traversaro** [fishbotics/urchin#2]
I was trying to package urchin for conda-forge in https://github.com/conda-forge/staged-recipes/pull/22592, and I noticed that urchin still has a strict pin of pycollada to 0.6.0 in https://github.com/fishbotics/urchin/blob/4d97ce752948795384b0d4209f1a169260878d7e/setup.py#L11 . This creates problem as pycollada 0.6.0 is not available in conda-forge. Is this strict pin intentional? 

@fishbotics

**Comment by fishbotics** [comment]
I didn't pin this for any specific reason. We can unpin it and test whether it breaks.

**Comment by fishbotics** [comment]
Which--relatedly--means we should probably add tests

**Comment by traversaro** [comment]
> Which--relatedly--means we should probably add tests

At least for running the tests that were already in urdfpy https://github.com/fishbotics/urchin/pull/1 should work fine.

**Comment by fishbotics** [comment]
I unpinned it with #4. I just pushed it without a MR because the change is so small, but in general, I'll stick to MRs.

**Comment by traversaro** [comment]
> I unpinned it with #4. I just pushed it without a MR because the change is so small, but in general, I'll stick to MRs.

Thanks!
