### ISSUE TITLE
Older style transmission type causes an AttributeError: 'NoneType'...

### ISSUE THREAD

**Issue by BuildingAtom** [fishbotics/urchin#9]
When using urchin to load a URDF with older-style transmission tags, Urchin crashes with:

```
...
  File ".../site-packages/urchin/urdf.py", line 2078, in _from_xml
    kwargs["trans_type"] = node.find("type").text
                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

This appears to be caused by the assumption that `type` must be an element, most likely based on [the current ROS page](http://wiki.ros.org/urdf/XML/Transmission), but this causes a crash for some files as the `type` is an attribute of the node instead (some examples can be found in [this discussion regarding the transmission tag](https://github.com/ros-simulation/gazebo_ros_pkgs/issues/52) linked by that ROS page).

One possible fix for that that I'm using at the moment is to check the node attributes first. I expand and edit [line 2078 of urdf.py](https://github.com/fishbotics/urchin/blob/main/urchin/urdf.py#L2078) so that the surrounding function now looks like:

```python
    @classmethod
    def _from_xml(cls, node, path):
        kwargs = cls._parse(node, path)
        try:
            trans_type = node.attrib.get('type')
            if trans_type is None:
                trans_type = node.find("type").text
            kwargs["trans_type"] = trans_type
        except AttributeError:
            kwargs["trans_type"] = ''
        return Transmission(**kwargs)
```

Though, this also makes the type optional (since it seems like it might not be required anyway?).

**Comment by fishbotics** [comment]
Hey @BuildingAtom , sorry I missed this issue! Can you file a PR with your changes? We should definitely support this use case

**Comment by BuildingAtom** [comment]
@fishbotics Sure thing! I just filed the PR.

**Comment by fishbotics** [comment]
Should be fixed by https://github.com/fishbotics/urchin/pull/14. Let me know if it's an issue. 

Thanks for contributing!
